service: fileset
runtime: nodejs10
env_variables:
  FILESET_SITE: default
  FILESET_LIVE_DOMAIN: example.com
  FILESET_STAGING_DOMAIN: '{ref}.staging.example.com'
  FILESET_ALLOWED_ORGANIZATIONS: 'example1.com,example2.com'
includes:
- secrets.yaml
handlers:
- url: /.*
  script: auto
  secure: always